name: TestAction

on:
    pull_request:
        types: [opened, reopened]

jobs:
    TestJob:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
          - name: send-test-to-pull-request
            uses: TaikiHoshika/ActionTest@v1
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}